### ISSUE TITLE
Possible problem with layers.basic.Upsample default align_corners kwarg.

### ISSUE THREAD

**Issue by boykovdn** [imagirom/ConfNets#1]
import confnets
model = confnets.UNet3d(depth=3, in_channels=1, out_channels=1, fmaps=[5,5,5,5])

Gave me the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-63b01d54f93c> in <module>
----> 1 model = confnets.UNet3d(depth=3, in_channels=1, out_channels=1, fmaps=[5,5,5,5])

~/anaconda3/lib/python3.7/site-packages/confnets/models/unet.py in __init__(self, conv_type, **super_kwargs)
    285     def __init__(self, conv_type='Conv3d', **super_kwargs):
    286         super_kwargs['conv_type'] = conv_type
--> 287         super(UNet3d, self).__init__(dim=3, **super_kwargs)
    288 
    289 

~/anaconda3/lib/python3.7/site-packages/confnets/models/unet.py in __init__(self, dim, scale_factor, conv_type, norm_type, activation, final_activation, upsampling_mode, skip_factor, *super_args, **super_kwargs)
    224         with torch.no_grad():
    225             inp = torch.zeros((2, self.in_channels, *self.divisibility_constraint), dtype=torch.float32)
--> 226             self(inp)
    227 
    228         # delete attributes that are only relevant for construction and might lead to errors when model is saved

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/confnets/models/unet.py in forward(self, input_)
    273             f'Input shape {input_.shape[2:]} not suited for downsampling with factors {self.scale_factors}.' \
    274             f'Lengths of spatial axes must be multiples of {self.divisibility_constraint}.'
--> 275         return super(UNet, self).forward(input_)
    276 
    277 

~/anaconda3/lib/python3.7/site-packages/confnets/models/unet.py in forward(self, input)
     48         for encoded_state, upsample, skip, merge, decode in reversed(list(zip(
     49                 encoded_states, self.upsampling_modules, self.skip_modules, self.merge_modules, self.decoder_modules))):
---> 50             current = upsample(current)
     51             encoded_state = skip(encoded_state)
     52             current = merge(current, encoded_state)

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/confnets/layers/basic.py in forward(self, input)
     71 
     72     def forward(self, input):
---> 73         return nn.functional.interpolate(input, scale_factor=self.scale_factor, mode=self.mode, align_corners=False)

~/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py in interpolate(input, size, scale_factor, mode, align_corners)
   2497     if mode in ('nearest', 'area'):
   2498         if align_corners is not None:
-> 2499             raise ValueError("align_corners option can only be set with the "
   2500                              "interpolating modes: linear | bilinear | bicubic | trilinear")
   2501     else:

ValueError: align_corners option can only be set with the interpolating modes: linear | bilinear | bicubic | trilinear
-----------------------------------------------------------------------

Changed layers.basic.Upsample, in forward, the parameter align_corners to None to avoid the error.

**Comment by imagirom** [comment]
Thanks for raising this Issue, will look at it later

**Comment by imagirom** [comment]
Should be fixed by bfaaf5d81c6bb5e989fefd00dcf49c5513b0c247. Let me know if you find any other problems :)
